spring:
  application:
    name: cards
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: configuser
      password: configpass