services:
  accounts:
    image: "bernietruong/accounts:accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - berniebank
  loans:
    image: "bernietruong/loans:loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - berniebank
  cards:
    image: "bernietruong/cards:cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - berniebank
networks:
  berniebank:
    driver: "bridge"