build:
  version: "2.0"

accounts:
  message: "Welcome to Bernie Bank accounts related QA APIs "
  contactDetails:
    name: "Bernie Truong - QA Lead"
    email: "bernie@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371