build:
  version: "1.0"

loans:
  message: "Welcome to Bernie Bank loans related prod APIs "
  contactDetails:
    name: "Bernie Truong - Product Owner"
    email: "bernie@gmail.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384