# Development environment configuration for Accounts Service
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

accounts:
  message: "Welcome to Bernie Bank accounts related development APIs "
  
logging:
  level:
    com.bernie.accounts: DEBUG
    org.springframework.web: DEBUG