# Common configuration for Loans Service
server:
  port: 8090

spring:
  application:
    name: loans
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: "loans"
    description: "Bernie Bank Loans Application"
    version: "1.0.0"

loans:
  message: "Welcome to Bernie Bank loans related local APIs "
  contactDetails:
    name: "Bernie Truong"
    email: "bernie@berniebank.com"